//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Maxim Skryabin (based on Juanpe Catalán's template)
//  Can be accessed at: https://github.com/moridaffy/VIPER-Xcode-template
//

class ___VARIABLE_productName:identifier___Router: ___VARIABLE_productName:identifier___RouterProtocol {
    
    var viewController: ___VARIABLE_productName:identifier___ViewController!
    
    init(viewController: ___VARIABLE_productName:identifier___ViewController) {
        self.viewController = viewController
    }
    
}
