//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Maxim Skryabin (based on Juanpe Catalán's template)
//  Can be accessed at: https://github.com/moridaffy/VIPER-Xcode-template
//

import UIKit

class ___VARIABLE_productName:identifier___Interactor: ___VARIABLE_productName:identifier___InteractorProtocol {

    var router: ___VARIABLE_productName:identifier___RouterProtocol!
    var presenter: ___VARIABLE_productName:identifier___PresenterProtocol!
    
    required init(presenter: ___VARIABLE_productName:identifier___PresenterProtocol) {
        self.presenter = presenter
    }
}
