//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Maxim Skryabin (based on Juanpe Catalán's template)
//  Can be accessed at: https://github.com/moridaffy/VIPER-Xcode-template
//

import UIKit

class ___VARIABLE_productName:identifier___ViewController: UIViewController, ___VARIABLE_productName:identifier___ViewProtocol {

	var presenter: ___VARIABLE_productName:identifier___PresenterProtocol!
    let configurator: ___VARIABLE_productName:identifier___ConfiguratorProtocol = ___VARIABLE_productName:identifier___Configurator()

	override func viewDidLoad() {
        super.viewDidLoad()
        configurator.configure(with: self)
        presenter.configureView()
    }

}
