//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Maxim Skryabin (based on Juanpe Catalán's template)
//  Can be accessed at: https://github.com/moridaffy/VIPER-Xcode-template
//

import UIKit

class ___VARIABLE_productName:identifier___Presenter: ___VARIABLE_productName:identifier___PresenterProtocol {

    var view: ___VARIABLE_productName:identifier___ViewProtocol!
    var router: ___VARIABLE_productName:identifier___RouterProtocol!
    var interactor: ___VARIABLE_productName:identifier___InteractorProtocol!
    
    required init(view: ___VARIABLE_productName:identifier___ViewProtocol) {
        self.view = view
    }
    
    func configureView() {
        
    }

}
